### ISSUE TITLE
Latest WsFederation beta nuget package is not compatible with IdentityServer3 release candidate

### ISSUE THREAD

**Issue by gnjack** [IdentityServer/IdentityServer3.WsFederation#41]
Hi,

When using IdentityServer3 version 2.0.0-rc1 and IdentityServer3.WsFederation version 2.0.0-beta1 the wsfed endpoint throws the exception:
````
Unhandled exceptionSystem.TypeLoadException: Could not load type 'IdentityServer3.Core.Extensions.OwinExtensions' from assembly 'IdentityServer3, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at IdentityServer3.WsFederation.WsFederationController.<Get>d__0.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at IdentityServer3.WsFederation.WsFederationController.Get() in c:\etc\Dropbox\identity\IdentityServer3\WsFederation\source\WsFederationPlugin\Configuration\Hosting\RequestResponseLogger.cs:line 0
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass12.<GetExecutor>b__8(Object instance, Object[] methodParameters) in c:\etc\Dropbox\thinktecture\IdentityModel\source\Core\Metadata\FederationMetadata.cs:line 0
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments) in c:\etc\Dropbox\thinktecture\IdentityModel\source\Core\Metadata\FederationMetadata.cs:line 0
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken) in c:\etc\Dropbox\identity\IdentityServer3\WsFederation\source\WsFederationPlugin\Configuration\Hosting\RequestResponseLogger.cs:line 0
````

IdentityServer3.Core.Extensions.OwinExtensions does not exist in the release candidate, this was changed to IdentityServer3.Core.Extensions.OwinEnvironmentExtensions in IdentityServer/IdentityServer3@948eebed and IdentityServer/IdentityServer3@766a3f9e

As far as I can tell, IdentityServer3.WsFederation just needs rebuilding against IdentityServer3 2.0.0-rc1?

**Comment by leastprivilege** [comment]
updated.

**Comment by leastprivilege** [comment]
Does it work for you?

**Comment by brockallen** [comment]
Any update?

**Comment by gnjack** [comment]
Thanks! This did resolve the problem, apologies for not updating the issue.
